"""Machine learning demand forecasting module.

Trains supervised ML models (XGBoost, Random Forest, Gradient Boosting) to forecast
'units_sold' using price signals, competitor pricing, promotions, and time features.
Includes evaluation functions for temporal test sets (MAE, RMSE, WAPE, R2).
"""

import logging
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, Union

import joblib
import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

# Try importing XGBoost
try:
    import xgboost as xgb
    XGBOOST_AVAILABLE = True
except ImportError:
    XGBOOST_AVAILABLE = False

# Try importing Facebook Prophet
try:
    from prophet import Prophet
    PROPHET_AVAILABLE = True
except ImportError:
    PROPHET_AVAILABLE = False

logger = logging.getLogger(__name__)

# Default feature subsets
DEFAULT_NUMERIC_FEATURES = [
    "current_price",
    "competitor_price",
    "discount_pct",
    "day_of_week",
    "day_of_month",
    "month",
    "is_weekend",
    "sin_day_of_week",
    "cos_day_of_week",
    "sin_month",
    "cos_month",
]

DEFAULT_CATEGORICAL_FEATURES = [
    "season",
    "category",
    "channel",
    "promotion_type",
]

# Optional lag/rolling features if generated by preprocessing
OPTIONAL_LAG_FEATURES = [
    "units_sold_lag_1",
    "units_sold_lag_7",
    "units_sold_lag_14",
    "units_sold_rolling_mean_7",
    "units_sold_rolling_std_7",
    "price_ratio_competitor",
    "unit_margin",
]


class ProphetForecaster:
    """Facebook Prophet Time-Series Demand Forecaster with uncertainty intervals.

    Decomposes demand into trend, weekly, and yearly seasonality.
    Provides point forecasts as well as 95% uncertainty intervals (yhat_lower, yhat_upper).
    """

    def __init__(
        self,
        date_col: str = "date",
        target_col: str = "units_sold",
        extra_regressors: Optional[List[str]] = None,
        interval_width: float = 0.95,
        yearly_seasonality: bool = False,
        weekly_seasonality: bool = True,
        daily_seasonality: bool = False,
        **prophet_kwargs: Any,
    ) -> None:
        if not PROPHET_AVAILABLE:
            raise ImportError("prophet package is required for ProphetForecaster.")
        self.date_col = date_col
        self.target_col = target_col
        self.extra_regressors = extra_regressors or []
        self.interval_width = interval_width
        self.yearly_seasonality = yearly_seasonality
        self.weekly_seasonality = weekly_seasonality
        self.daily_seasonality = daily_seasonality
        self.prophet_kwargs = prophet_kwargs
        self.model: Optional[Any] = None
        self.fitted_regressors_: List[str] = []

    def fit(self, train_df: pd.DataFrame) -> "ProphetForecaster":
        """Fit Prophet model on historical training dataframe."""
        df = train_df.copy()
        if self.date_col in df.columns:
            df["ds"] = pd.to_datetime(df[self.date_col])
        elif "ds" in df.columns:
            df["ds"] = pd.to_datetime(df["ds"])
        else:
            df["ds"] = pd.date_range(end=pd.Timestamp.today(), periods=len(df), freq="D")

        df["y"] = df[self.target_col].astype(float)

        self.model = Prophet(
            interval_width=self.interval_width,
            yearly_seasonality=self.yearly_seasonality,
            weekly_seasonality=self.weekly_seasonality,
            daily_seasonality=self.daily_seasonality,
            **self.prophet_kwargs,
        )

        self.fitted_regressors_ = []
        for reg in self.extra_regressors:
            if reg in df.columns and not df[reg].isna().all():
                self.model.add_regressor(reg)
                self.fitted_regressors_.append(reg)

        cols_to_keep = ["ds", "y"] + self.fitted_regressors_
        prophet_df = df[cols_to_keep].dropna().sort_values("ds")
        try:
            import cmdstanpy
            cmdstanpy.utils.get_logger().disabled = True
        except Exception:
            pass
        self.model.fit(prophet_df)
        return self

    def predict_with_intervals(self, test_df: pd.DataFrame) -> pd.DataFrame:
        """Return point forecast with lower and upper confidence intervals."""
        if self.model is None:
            raise ValueError("ProphetForecaster must be fitted before predict.")
        df = test_df.copy()
        if self.date_col in df.columns:
            df["ds"] = pd.to_datetime(df[self.date_col])
        elif "ds" in df.columns:
            df["ds"] = pd.to_datetime(df["ds"])
        else:
            df["ds"] = pd.date_range(start=pd.Timestamp.today(), periods=len(df), freq="D")

        cols = ["ds"] + [r for r in self.fitted_regressors_ if r in df.columns]
        future_df = df[cols].copy()
        forecast = self.model.predict(future_df)
        forecast["yhat"] = np.maximum(0.0, forecast["yhat"])
        forecast["yhat_lower"] = np.maximum(0.0, forecast["yhat_lower"])
        forecast["yhat_upper"] = np.maximum(0.0, forecast["yhat_upper"])
        return forecast[["ds", "yhat", "yhat_lower", "yhat_upper"]].reset_index(drop=True)

    def predict(self, test_df: pd.DataFrame) -> np.ndarray:
        """Return 1D numpy array of point forecasts."""
        res = self.predict_with_intervals(test_df)
        return res["yhat"].values


class DemandForecaster:
    """Supervised demand forecasting model pipeline.

    Wraps scikit-learn preprocessing and regressor (XGBoost, Random Forest, Linear Regression, or Prophet)
    into an end-to-end reproducible estimator.
    """

    def __init__(
        self,
        model_type: str = "xgboost",
        numeric_features: Optional[List[str]] = None,
        categorical_features: Optional[List[str]] = None,
        random_state: int = 42,
        **model_params: Any,
    ) -> None:
        """Initialize demand forecaster.

        Parameters
        ----------
        model_type : str, optional
            'xgboost', 'random_forest', 'gradient_boosting', 'linear_regression', or 'prophet', by default "xgboost".
        numeric_features : Optional[List[str]], optional
            List of numeric predictor columns.
        categorical_features : Optional[List[str]], optional
            List of categorical predictor columns.
        random_state : int, optional
            Seed for reproducibility, by default 42.
        **model_params : Any
            Additional hyperparameters forwarded to the base regressor.
        """
        self.model_type = model_type.lower()
        self.random_state = random_state
        self.numeric_features = numeric_features or list(DEFAULT_NUMERIC_FEATURES)
        self.categorical_features = categorical_features or list(DEFAULT_CATEGORICAL_FEATURES)
        self.model_params = model_params

        self.pipeline: Optional[Pipeline] = None
        self.prophet_model_: Optional[ProphetForecaster] = None
        self.residual_std_: float = 1.0
        self.fitted_numeric_features_: List[str] = []
        self.fitted_categorical_features_: List[str] = []

    def _build_regressor(self) -> Any:
        """Instantiate the underlying regressor algorithm."""
        if self.model_type == "xgboost":
            if not XGBOOST_AVAILABLE:
                logger.warning("XGBoost not installed. Falling back to RandomForestRegressor.")
                return RandomForestRegressor(
                    n_estimators=100,
                    random_state=self.random_state,
                    n_jobs=-1,
                    **self.model_params,
                )
            default_params = {
                "n_estimators": 150,
                "learning_rate": 0.08,
                "max_depth": 6,
                "subsample": 0.8,
                "colsample_bytree": 0.8,
                "random_state": self.random_state,
                "n_jobs": -1,
            }
            default_params.update(self.model_params)
            return xgb.XGBRegressor(**default_params)

        elif self.model_type == "random_forest":
            default_params = {
                "n_estimators": 100,
                "max_depth": 12,
                "random_state": self.random_state,
                "n_jobs": -1,
            }
            default_params.update(self.model_params)
            return RandomForestRegressor(**default_params)

        elif self.model_type == "gradient_boosting":
            default_params = {
                "n_estimators": 100,
                "learning_rate": 0.1,
                "max_depth": 5,
                "random_state": self.random_state,
            }
            default_params.update(self.model_params)
            return GradientBoostingRegressor(**default_params)

        elif self.model_type == "linear_regression":
            return LinearRegression(**self.model_params)

        elif self.model_type == "prophet":
            # Handled separately in fit/predict
            return None

        else:
            raise ValueError(
                f"Unsupported model_type: '{self.model_type}'. Choose 'xgboost', 'random_forest', 'gradient_boosting', 'linear_regression', or 'prophet'."
            )

    def _prepare_feature_columns(self, df: pd.DataFrame) -> Tuple[List[str], List[str]]:
        """Filter configured features to those actually present in the input DataFrame."""
        # Include optional lag features if present in df
        potential_numerics = self.numeric_features + [
            f for f in OPTIONAL_LAG_FEATURES if f not in self.numeric_features
        ]
        active_numerics = [f for f in potential_numerics if f in df.columns]
        active_categoricals = [f for f in self.categorical_features if f in df.columns]

        logger.info(
            "Selected %d numeric features and %d categorical features for training.",
            len(active_numerics),
            len(active_categoricals),
        )
        return active_numerics, active_categoricals

    def fit(
        self,
        train_df: pd.DataFrame,
        target_col: str = "units_sold",
    ) -> "DemandForecaster":
        """Fit the demand forecasting pipeline on training data.

        Parameters
        ----------
        train_df : pd.DataFrame
            Preprocessed training dataset.
        target_col : str, optional
            Target column to predict, by default "units_sold".

        Returns
        -------
        DemandForecaster
            Fitted estimator instance.
        """
        if target_col not in train_df.columns:
            raise KeyError(f"Target column '{target_col}' not found in training DataFrame.")

        if self.model_type == "prophet":
            logger.info("Training Prophet Forecaster on %d samples...", len(train_df))
            date_c = "date" if "date" in train_df.columns else "ds"
            extra_r = ["current_price"] if "current_price" in train_df.columns else []
            self.prophet_model_ = ProphetForecaster(
                date_col=date_c,
                target_col=target_col,
                extra_regressors=extra_r,
            )
            self.prophet_model_.fit(train_df)
            y_train = train_df[target_col].values
            y_pred_train = self.prophet_model_.predict(train_df)
            self.residual_std_ = max(0.1, float(np.std(y_train - y_pred_train)))
            return self

        self.fitted_numeric_features_, self.fitted_categorical_features_ = (
            self._prepare_feature_columns(train_df)
        )

        # Preprocessing transformers
        transformers = []
        if self.fitted_numeric_features_:
            transformers.append(
                ("num", StandardScaler(), self.fitted_numeric_features_)
            )

        if self.fitted_categorical_features_:
            transformers.append(
                (
                    "cat",
                    OneHotEncoder(handle_unknown="ignore", sparse_output=False),
                    self.fitted_categorical_features_,
                )
            )

        preprocessor = ColumnTransformer(transformers=transformers, remainder="drop")
        regressor = self._build_regressor()

        self.pipeline = Pipeline(
            steps=[
                ("preprocessor", preprocessor),
                ("regressor", regressor),
            ]
        )

        X_train = train_df[self.fitted_numeric_features_ + self.fitted_categorical_features_]
        y_train = train_df[target_col].values

        logger.info(
            "Training %s regressor on %d samples with %d features...",
            self.model_type.upper(),
            len(train_df),
            len(self.fitted_numeric_features_) + len(self.fitted_categorical_features_),
        )
        self.pipeline.fit(X_train, y_train)
        y_pred_train = np.clip(self.pipeline.predict(X_train), a_min=0.0, a_max=None)
        self.residual_std_ = max(0.1, float(np.std(y_train - y_pred_train)))
        logger.info("Model training successfully completed. Residual std: %.4f", self.residual_std_)

        return self

    def predict(self, df: pd.DataFrame) -> np.ndarray:
        """Generate demand forecasts for the given DataFrame.

        Enforces non-negative demand (clipping at 0).

        Parameters
        ----------
        df : pd.DataFrame
            DataFrame containing the required predictor columns.

        Returns
        -------
        np.ndarray
            Predicted demand array.
        """
        if self.model_type == "prophet":
            if self.prophet_model_ is None:
                raise RuntimeError("Prophet model must be fitted before calling predict().")
            return self.prophet_model_.predict(df)

        if self.pipeline is None:
            raise RuntimeError("Model must be fitted before calling predict().")

        features = self.fitted_numeric_features_ + self.fitted_categorical_features_
        missing_cols = [c for c in features if c not in df.columns]
        if missing_cols:
            raise KeyError(f"Input DataFrame is missing required predictor columns: {missing_cols}")

        X = df[features]
        preds = self.pipeline.predict(X)
        # Demand cannot be strictly negative in retail
        return np.clip(preds, a_min=0.0, a_max=None)

    def predict_with_intervals(
        self, df: pd.DataFrame, alpha: float = 0.05
    ) -> pd.DataFrame:
        """Generate demand forecasts with lower and upper confidence intervals.

        Parameters
        ----------
        df : pd.DataFrame
            DataFrame containing predictor columns.
        alpha : float, optional
            Significance level (default 0.05 for 95% confidence interval).

        Returns
        -------
        pd.DataFrame
            DataFrame with ['ds', 'yhat', 'yhat_lower', 'yhat_upper'].
        """
        if self.model_type == "prophet":
            if self.prophet_model_ is None:
                raise RuntimeError("Prophet model must be fitted before calling predict().")
            return self.prophet_model_.predict_with_intervals(df)

        point_preds = self.predict(df)
        z = 1.96 if alpha == 0.05 else 1.645
        half_width = z * self.residual_std_

        date_col = "date" if "date" in df.columns else ("ds" if "ds" in df.columns else None)
        ds_vals = df[date_col] if date_col is not None else pd.RangeIndex(len(df))

        return pd.DataFrame(
            {
                "ds": ds_vals,
                "yhat": point_preds,
                "yhat_lower": np.maximum(0.0, point_preds - half_width),
                "yhat_upper": point_preds + half_width,
            }
        ).reset_index(drop=True)

    def get_feature_importances(self) -> pd.DataFrame:
        """Extract and rank feature importances from the fitted regressor.

        Returns
        -------
        pd.DataFrame
            DataFrame of features and their importance scores, sorted descending.
        """
        if self.pipeline is None:
            raise RuntimeError("Model must be fitted before extracting feature importances.")

        preprocessor = self.pipeline.named_steps["preprocessor"]
        regressor = self.pipeline.named_steps["regressor"]

        feature_names = []
        if self.fitted_numeric_features_:
            feature_names.extend(self.fitted_numeric_features_)
        if self.fitted_categorical_features_:
            cat_encoder = preprocessor.named_transformers_["cat"]
            feature_names.extend(
                cat_encoder.get_feature_names_out(self.fitted_categorical_features_).tolist()
            )

        if hasattr(regressor, "feature_importances_"):
            importances = regressor.feature_importances_
            df_imp = pd.DataFrame(
                {"feature": feature_names, "importance": importances}
            ).sort_values(by="importance", ascending=False).reset_index(drop=True)
            return df_imp
        else:
            logger.warning("Regressor does not expose feature_importances_ attribute.")
            return pd.DataFrame(columns=["feature", "importance"])

    def save(self, filepath: Union[str, Path]) -> None:
        """Persist fitted model pipeline to disk."""
        filepath = Path(filepath)
        filepath.parent.mkdir(parents=True, exist_ok=True)
        joblib.dump(self, filepath)
        logger.info("Model pipeline persisted to %s", filepath)

    @classmethod
    def load(cls, filepath: Union[str, Path]) -> "DemandForecaster":
        """Load persisted model pipeline from disk."""
        filepath = Path(filepath)
        if not filepath.exists():
            raise FileNotFoundError(f"Model checkpoint not found at: {filepath}")
        model = joblib.load(filepath)
        logger.info("Loaded model pipeline from %s", filepath)
        return model


# -------------------------------------------------------------------------
# Evaluation Function
# -------------------------------------------------------------------------

def evaluate_forecast(
    y_true: np.ndarray,
    y_pred: np.ndarray,
) -> Dict[str, float]:
    """Calculate key forecast accuracy metrics (MAE, RMSE, WAPE, R2).

    Parameters
    ----------
    y_true : np.ndarray
        Ground-truth demand values.
    y_pred : np.ndarray
        Predicted demand values.

    Returns
    -------
    Dict[str, float]
        Dictionary containing calculated metrics.
    """
    y_true = np.asarray(y_true, dtype=float)
    y_pred = np.asarray(y_pred, dtype=float)

    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)

    # Weighted Absolute Percentage Error (industry retail KPI)
    total_true = np.sum(y_true)
    wape = (np.sum(np.abs(y_true - y_pred)) / total_true) * 100.0 if total_true > 0 else 0.0

    # Mean Absolute Percentage Error (with epsilon for zero true demand)
    nonzero_mask = y_true > 0
    if np.any(nonzero_mask):
        mape = np.mean(np.abs((y_true[nonzero_mask] - y_pred[nonzero_mask]) / y_true[nonzero_mask])) * 100.0
    else:
        mape = 0.0

    metrics = {
        "mae": round(float(mae), 4),
        "rmse": round(float(rmse), 4),
        "wape_pct": round(float(wape), 2),
        "mape_pct": round(float(mape), 2),
        "r2_score": round(float(r2), 4),
    }

    logger.info(
        "Forecast Evaluation -> MAE: %.4f | RMSE: %.4f | WAPE: %.2f%% | R2: %.4f",
        metrics["mae"],
        metrics["rmse"],
        metrics["wape_pct"],
        metrics["r2_score"],
    )
    return metrics


def evaluate_temporal_test(
    model: DemandForecaster,
    test_df: pd.DataFrame,
    target_col: str = "units_sold",
) -> Tuple[Dict[str, float], pd.DataFrame]:
    """Evaluate a trained model on a temporal holdout test dataset.

    Parameters
    ----------
    model : DemandForecaster
        Fitted demand forecaster instance.
    test_df : pd.DataFrame
        Chronologically partitioned test DataFrame.
    target_col : str, optional
        Ground-truth column name, by default "units_sold".

    Returns
    -------
    Tuple[Dict[str, float], pd.DataFrame]
        Metrics dictionary and DataFrame with actual vs predicted values.
    """
    logger.info("Evaluating forecaster on temporal test set (%d samples)...", len(test_df))
    y_true = test_df[target_col].values
    y_pred = model.predict(test_df)

    metrics = evaluate_forecast(y_true, y_pred)

    results_df = test_df.copy()
    results_df["predicted_units_sold"] = np.round(y_pred, 2)
    results_df["absolute_error"] = np.round(np.abs(y_true - y_pred), 2)

    return metrics, results_df
